
spring:
  config:
    import: optional:secrets.yml
  security:
    user:
      password: 123
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #fix table replace with lowercase automatic and _
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  main:
    banner-mode: off
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 25MB
  mail:
    host: smtp.hostinger.com
    port: 465
    username: jobhunter@modundo.com
    password: '@Jobhunter2003'
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
server:
  port: 80