spring:
  security:
    user:
      password: 123
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Application_Job;encrypt=true;trustServerCertificate=true
    Username: sa
    password: khanhuy123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    database: sql_server
    database-platform: org.hibernate.dialect. PostgreSQLDialect
  main:
    banner-mode: off
server:
  port: 8080
