
spring:
  config:
    import: optional:secrets.yml
  security:
    user:
      password: 123
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #fix table replace with lowercase automatic and _
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  main:
    banner-mode: off
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  port: 80