spring:
  datasource:
    url: jdbc:sqlserver://blackundozz.database.windows.net:1433;databaseName=Job_Application;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    Username: vip
    password: '@Panda20032023'
application:
  security:
    verify:
      expiration: 240000 # 15 miu
    jwt:
      secret-key: EA4D0954F62668B7305D70FBEAE824A06BAA6B93AB7AD1DB4C1DAD5ED981BCF6
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days