name: Maven Package and Service Reset

on:
  push:
    branches:
      - huydev # Thay đổi tên branch tùy vào tên branch của bạn

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '17'

      # - name: cd into backend
      #   run: cd BackEnd_Job_Website

      # - name: Build with Maven
      #   run: mvn clean package

      - name: SSH to Server and Reset
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }} # Thay đổi bằng địa chỉ IP của server
          username: ${{ secrets.SERVER_USERNAME }} # Thay đổi bằng tên người dùng SSH
          #password: ${{ secrets.SERVER_PASSWORD }} # Sử dụng SSH key nếu có thể
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/ubuntu/Job-Application-Web-Project/BackEnd_Job_Website/ && /opt/apache-maven-3.6.3/bin/mvn package
            sudo systemctl restart Job_Hunter_SpringBoot
